### ISSUE TITLE
Updated authenticator configuration for OpenID Connect?

### ISSUE THREAD

**Issue by michelau** [boylesoftware/tomcat-openidauth#5]
When I try to use the sample config from the README for authenticating with Google, I see this in the debug logs:

    12-Apr-2017 02:47:54.129 FINE [http-nio-8443-exec-3] org.bsworks.catalina.authenticator.openid.OpenIDAuthenticator$1.log HTTP error 404: https://www.google.com/accounts/o8/id
    java.io.FileNotFoundException: https://www.google.com/accounts/o8/id

Per https://developers.google.com/identity/protocols/OpenID2Migration#adjust-uri that URI isn't valid anymore.

Does the plugin support OpenID Connect?

**Comment by levahim** [comment]
This authenticator is for OpenID 2.0 only. For OpenID Connect take a look at https://github.com/boylesoftware/tomcat8-oidcauth.

**Comment by michelau** [comment]
Thank you very much!
